// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Abeemmss",
    "email": "abemss666@mail.com",
    "password": "1",
    "confirmPassword": "1",
    "role": "admin"
}

###
// Update User
PATCH  http://localhost:5000/users/62667e65-0c80-4514-82e8-7364b898efbc
Content-Type: application/json

{
    "name": "Abeemmss UPDATED",
    "email": "abem666@mail.com",
    "password": "1",
    "confirmPassword": "1",
    "role": "admin"
}

###
// Update User
DELETE   http://localhost:5000/users/62667e65-0c80-4514-82e8-7364b898efbc

###
# Get All Users 
GET http://localhost:5000/users

###
# Get All Users by uuid
GET http://localhost:5000/users/41a5d714-2953-428a-b374-ded480eec66c

###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "abemss666@mail.com",
    "password": "1"
}

###
// Login as user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "abem666@mail.com",
    "password": "1"
}

###
// Me
GET  http://localhost:5000/me

###
// Logout
DELETE http://localhost:5000/logout


# Product

# Get All Product
###
GET  http://localhost:5000/products

# Get product by id
###
GET  http://localhost:5000/products/7b7640a7-b0c3-4710-ab97-649fb12cda0e

# Create Product
###
POST  http://localhost:5000/products
Content-Type: application/json

{
    "name": "Produk 1",
    "price": 40000
}

# Update Product
###
PATCH   http://localhost:5000/products/7b7640a7-b0c3-4710-ab97-649fb12cda0e
Content-Type: application/json

{
    "name": "Produk 1",
    "price": 40000
}

# Delete Product
###
DELETE    http://localhost:5000/products/7b7640a7-b0c3-4710-ab97-649fb12cda0e